### ISSUE TITLE
On Linux Debian 32-bits, the compilation terminate on stdafx.h not found

### ISSUE THREAD

**Issue by goupildb** [RegrowthStudios/SoACode-Public#1]
On Linux Debian 32-bits, the compilation terminate on SoA/stdafx.h:18:10: fatal error

$ cd SoA
$ ./build.sh
(...)
Built target doc
Scanning dependencies of target soa
[  1%] Building CXX object CMakeFiles/soa.dir/AABBCollidableComponentUpdater.cpp.o
In file included from /mnt/DDprc/Download/repos/soa/SoA/AABBCollidableComponentUpdater.cpp:1:0:
/mnt/DDprc/Download/repos/soa/SoA/stdafx.h:18:10: fatal error: Vorb/stdafx.h: Aucun fichier ou dossier de ce type
 #include <Vorb/stdafx.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/soa.dir/build.make:62 : la recette pour la cible « CMakeFiles/soa.dir/AABBCollidableComponentUpdater.cpp.o » a échouée
make[2]: *** [CMakeFiles/soa.dir/AABBCollidableComponentUpdater.cpp.o] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/soa.dir/all » a échouée
make[1]: *** [CMakeFiles/soa.dir/all] Erreur 2
Makefile:140 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Effectively, stdafx.h seems to be no longer in Vorb/, but there is a file named stdafx.h in Vorb/include/
So, in soa/SoA/stdafx.h, i have try to change: #include <Vorb/stdafx.h>
by: #include <Vorb/include/stdafx.h>

but it doesn't work:
(...)
Scanning dependencies of target soa
[  1%] Building CXX object CMakeFiles/soa.dir/AABBCollidableComponentUpdater.cpp.o
In file included from /mnt/DDprc/Download/repos/soa/SoA/AABBCollidableComponentUpdater.cpp:1:0:
/mnt/DDprc/Download/repos/soa/SoA/stdafx.h:18:10: fatal error: deps/Vorb/include/stdafx.h: Aucun fichier ou dossier de ce type

Yet this file remains well in Vorb/include/
I don't understand (but my knowledge on compilation are very limited).

**Comment by brianbruggeman** [comment]
Vorb and SoA won't compile immediately on Mac or Linux without some work.  While we strived to create something that was cross platform, most of us were on a Windows box and only one of us had access to a Mac.  And given the state of the project, updates for non-Windows won't be for quite some time if an update happens...

`stdafx.h` is a Visual Studio specific file and pretty useless on non Windows systems.  I don't think you can add an empty file, but it should be a fairly trivial port if you wanted to dig into it.

**Comment by caseymcc** [comment]
Going to close this as changes have been made to specify what it compiles on (and linux is one of them).
