### ISSUE TITLE
Discord server.

### ISSUE THREAD

**Issue by caseymcc** [RegrowthStudios/SoACode-Public#3]
I couldn't locate a slack/discord server for SoA and I thought it might be worthwhile so I created one.

https://discord.gg/QRex8GK

**Comment by Barnold1953** [comment]
I'm getting "The instant invite is invalid or has expired"

**Comment by caseymcc** [comment]
updated link, forgot to make it never expire

**Comment by caseymcc** [comment]
added to readme
