### ISSUE TITLE
Size of SCRayNode is not 24

### ISSUE THREAD

**Issue by JackalopeGit** [RegrowthStudios/SoACode-Public#8]
`struct SCRayNode {

    SCRayNode(const f32v3& pos, ui16 parent, ui16 trunkPropsIndex) :

        pos(pos), trunkPropsIndex(trunkPropsIndex), wasVisited(false), parent(parent){};

    f32v3 pos;

    struct {

        ui16 trunkPropsIndex : 15;

        bool wasVisited : 1;

    };

    ui16 parent;

    f32 width = 1.0f;

};

static_assert(sizeof(SCRayNode) == 24, "Size of SCRayNode is not 24");`

Flora generator assert. 
This is 20 byte struct, it can't be 24, where should be the alignment?

**Comment by Barnold1953** [comment]
Likely an unused variable was deleted. I don't think this was intended to check for alignment but rather an attempt to keep it from growing and keep strong cache coherency. You can safely delete or adjust the assert.
